name: ChenWuWanCheck

on:
  schedule:
  - cron: "15 1,2,6,7,12,13 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8
          
      - name: Install Requests
        run: |
          pip install requests
          
      - name: Signup
        run: python checkin.py
